language: ruby
rvm:
  - "2.3.4"
before_install:
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.4.3.deb && sudo dpkg -i --force-confnew elasticsearch-6.4.3.deb
  - sudo -i service elasticsearch start
script:
  - bundle exec cucumber features/
